export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";


export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR"



export const NEW_ALBUM_REQUEST = "NEW_ALBUM_REQUEST";
export const NEW_ALBUM_SUCCESS = "NEW_ALBUM_SUCCESS";
export const NEW_ALBUM_RESET = "NEW_ALBUM_RESET";
export const NEW_ALBUM_FAIL = "NEW_ALBUM_FAIL";

export const ALL_ALBUM_REQUEST = "ALL_ALBUM_REQUEST";
export const ALL_ALBUM_SUCCESS = "ALL_ALBUM_SUCCESS";
export const ALL_ALBUM_RESET = "ALL_ALBUM_RESET";
export const ALL_ALBUM_FAIL = "ALL_ALBUM_FAIL";

export const ALBUM_DETAILS_REQUEST = "ALBUM_DETAILS_REQUEST";
export const ALBUM_DETAILS_SUCCESS = "ALBUM_DETAILS_SUCCESS";
export const ALBUM_DETAILS_FAIL = "ALBUM_DETAILS_FAIL";

export const UPDATE_ALBUM_REQUEST = "UPDATE_ALBUM_REQUEST";
export const UPDATE_ALBUM_SUCCESS = "UPDATE_ALBUM_SUCCESS";
export const UPDATE_ALBUM_RESET = "UPDATE_ALBUM_RESET";
export const UPDATE_ALBUM_FAIL = "UPDATE_ALBUM_FAIL";

export const DELETE_ALBUM_REQUEST = "DELETE_ALBUM_REQUEST";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_RESET = "DELETE_ALBUM_RESET";
export const DELETE_ALBUM_FAIL = "DELETE_ALBUM_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";